### PR TITLE
Fixed an issue that I caused by modifying a update function

### PR DESCRIPTION
**Pull request by omagarwal25**
I had changed the function to one that outputs a pair of values instead of one that outputs all four rotations. This should fix it.

### CODE REVIEW

**Comment by amarcolini** [comment]
Fixed in latest commit.

**Comment by omagarwal25** [comment]
@amarcolini there is still an issue where it will reverse if the gears are 275. You can fix that by just checking if the difference is not in the range of negative half positive positive half pi.

**Comment by amarcolini** [comment]
What do you mean by the gears being 275?

**Comment by omagarwal25** [comment]
Them being ofset by 275 degrees or 1.6 radians

**Comment by amarcolini** [comment]
Here's the relevant part of the code :
```kotlin
((leftModuleController.targetPosition - leftOrientation.radians).wrap(-PI, PI) <= (PI * 0.5))
```
It doesn't seem to have that problem.

**Comment by omagarwal25** [comment]
If the target is -.7PI and the module is at 0, although they are not within .5 PI of eachother the code would still not reverse them.

-.7PI-0 = -.7PI

Wrapped that would stay the same.

Although the values are further than .5PI away from eachother, it is still less than PI/2 and therefore doesn't get reversed. 

I hope that makes sense.


The way would fix this is instead just checking if it's less than PI/2 you can check if it's in the range of -.5PI...5PI.

**Comment by omagarwal25** [comment]
`val sameHalf = abs(target.wrap(-PI, PI) - current.wrap(-PI, PI)) !in (PI / 2)..(3 * PI / 2)` was my solution to the issue, but 

`((leftModuleController.targetPosition - leftOrientation.radians).wrap(-PI, PI) in (PI * -0.5)..(PI * 0.5))` would work just fine.

**Comment by amarcolini** [comment]
Oh. I forgot the absolute value. It was supposed to look like this:
```kotlin
(abs((leftModuleController.targetPosition - leftOrientation.radians).wrap(-PI, PI)) <= (PI * 0.5))
```

**Comment by omagarwal25** [comment]
I'll test that tonight.

**Comment by omagarwal25** [comment]
Okay so, it works. However, can I make the gears field and other methods public or at least not private (protected would work) so that I can access them for telemetry? Otherwise I would have to keep a copy of the motors in the robot class to use and that sounds annoying.

**Comment by amarcolini** [comment]
You mean like the `motors` field in the other drives?

**Comment by omagarwal25** [comment]
Well the `gears` field for swerve but yeah. I want to be able to output some values onto the dashboard for easier tunning.

**Comment by amarcolini** [comment]
Check the latest commit and see if that works for you

**Comment by omagarwal25** [comment]
It works :), might want to add a angle method or something.

**Comment by amarcolini** [comment]
To get the module orientations?

**Comment by omagarwal25** [comment]
No just the field in the motor class, I can do kinematics myself.

**Comment by amarcolini** [comment]
The `rotation` field?

**Comment by omagarwal25** [comment]
Yeah.

**Comment by omagarwal25** [comment]
I got it. I just mapped it.

**Pull request closed without merging**
